// ═══ RecruitOS UI Component Library ═══
// New R-prefixed components (preferred)

export { default as RButton } from './button/RButton.vue'
export { default as RCard } from './card/RCard.vue'
export { default as RBadge } from './badge/RBadge.vue'
export { default as RInput } from './input/RInput.vue'
export { default as RTextarea } from './textarea/RTextarea.vue'
export { default as RSelect } from './select/RSelect.vue'
export { default as RCheckbox } from './checkbox/RCheckbox.vue'
export { default as RRadio } from './radio/RRadio.vue'
export { default as RRadioGroup, default as RRadioGroupItem } from './radio/RRadio.vue'
export { default as RSwitch } from './switch/RSwitch.vue'
export { default as RTable } from './table/RTable.vue'
export { default as RTableHead } from './table/RTableHead.vue'
export { default as RTableBody } from './table/RTableBody.vue'
export { default as RTableRow } from './table/RTableRow.vue'
export { default as RTableTh } from './table/RTableTh.vue'
export { default as RTableCell } from './table/RTableCell.vue'
export { default as RTabs } from './tabs/RTabs.vue'
export { default as RTabsList } from './tabs/RTabsList.vue'
export { default as RTabsTrigger } from './tabs/RTabsTrigger.vue'
export { default as RTabsContent } from './tabs/RTabsContent.vue'
export { default as RDialog } from './dialog/RDialog.vue'
export { default as RDialogContent } from './dialog/DialogContent.vue'
export { default as RDialogHeader } from './dialog/DialogHeader.vue'
export { default as RDialogTitle } from './dialog/DialogTitle.vue'
export { default as RDialogFooter } from './dialog/DialogFooter.vue'
export { default as RDrawer } from './drawer/RDrawer.vue'
export { default as RDrawerContent } from './drawer/DrawerContent.vue'
export { default as RSheet } from './drawer/RDrawer.vue'
export { default as RSheetContent } from './drawer/DrawerContent.vue'
export { default as RTooltip } from './tooltip/RTooltip.vue'
export { default as RProgress } from './progress/RProgress.vue'
export { default as RAvatar } from './avatar/RAvatar.vue'
export { default as RAvatarImage } from './avatar/RAvatar.vue'
export { default as RAvatarFallback } from './avatar/RAvatar.vue'
export { default as RSkeleton } from './skeleton/RSkeleton.vue'
export { default as REmpty } from './empty/REmpty.vue'
export { default as RToast } from './toast/RToast.vue'
export { default as RPagination } from './pagination/RPagination.vue'
export { default as RAlert } from './alert/RAlert.vue'
export { default as RAlertTitle } from './alert/AlertTitle.vue'
export { default as RAlertDescription } from './alert/AlertDescription.vue'
export { default as RDropdown } from './dropdown/RDropdown.vue'
export { default as RDropdownTrigger } from './dropdown/RDropdown.vue'
export { default as RDropdownContent } from './dropdown/RDropdown.vue'
export { default as RDropdownMenuItem } from './dropdown/RDropdown.vue'
export { default as RSeparator } from './separator/RSeparator.vue'
export { default as RScrollArea } from './scroll-area/RScrollArea.vue'
export { default as RLabel } from './label/RLabel.vue'
export { default as RPageShell } from './page-shell/RPageShell.vue'

// ═══ Backward-compatible aliases (deprecated, migrate to R-prefixed) ═══

export { default as Button } from './button/RButton.vue'
export { default as Card } from './card/RCard.vue'
export { default as CardHeader } from './card/CardHeader.vue'
export { default as CardTitle } from './card/CardTitle.vue'
export { default as CardContent } from './card/CardContent.vue'
export { default as CardFooter } from './card/CardFooter.vue'
export { default as Badge } from './badge/RBadge.vue'
export { default as Input } from './input/RInput.vue'
export { default as Textarea } from './textarea/RTextarea.vue'
export { default as Select } from './select/RSelect.vue'
export { default as Checkbox } from './checkbox/RCheckbox.vue'
export { default as RadioGroup, default as RadioGroupItem } from './radio/RRadio.vue'
export { default as Switch } from './switch/RSwitch.vue'
export { default as Table } from './table/RTable.vue'
export { default as TableHeader } from './table/RTableHead.vue'
export { default as TableBody } from './table/RTableBody.vue'
export { default as TableRow } from './table/RTableRow.vue'
export { default as TableHead } from './table/RTableTh.vue'
export { default as TableCell } from './table/RTableCell.vue'
export { default as Tabs } from './tabs/RTabs.vue'
export { default as TabsList } from './tabs/RTabsList.vue'
export { default as TabsTrigger } from './tabs/RTabsTrigger.vue'
export { default as TabsContent } from './tabs/RTabsContent.vue'
export { default as Dialog } from './dialog/RDialog.vue'
export { default as DialogContent } from './dialog/DialogContent.vue'
export { default as DialogHeader } from './dialog/DialogHeader.vue'
export { default as DialogTitle } from './dialog/DialogTitle.vue'
export { default as DialogFooter } from './dialog/DialogFooter.vue'
export { default as Sheet } from './drawer/RDrawer.vue'
export { default as SheetContent } from './drawer/DrawerContent.vue'
export { default as Tooltip } from './tooltip/RTooltip.vue'
export { default as Progress } from './progress/RProgress.vue'
export { default as Avatar, default as AvatarImage, default as AvatarFallback } from './avatar/RAvatar.vue'
export { default as Skeleton } from './skeleton/RSkeleton.vue'
export { default as Pagination } from './pagination/RPagination.vue'
export { default as Alert } from './alert/RAlert.vue'
export { default as AlertTitle } from './alert/AlertTitle.vue'
export { default as AlertDescription } from './alert/AlertDescription.vue'
export { default as DropdownMenu, default as DropdownMenuTrigger, default as DropdownMenuContent, default as DropdownMenuItem } from './dropdown/RDropdown.vue'
export { default as Separator } from './separator/RSeparator.vue'
export { default as ScrollArea } from './scroll-area/RScrollArea.vue'
export { default as Label } from './label/RLabel.vue'
