// ═══ RecruitOS UI Component Library ═══
// New R-prefixed components (preferred)

export { default as RButton } from './button/RButton.vue'
export { default as RCard } from './card/RCard.vue'
export { default as RBadge } from './badge/RBadge.vue'
export { default as RInput } from './input/RInput.vue'
export { default as RTextarea } from './textarea/RTextarea.vue'
export { default as RSelect } from './select/RSelect.vue'
export { default as RCheckbox } from './checkbox/RCheckbox.vue'
export { default as RRadio, default as RRadioGroup, default as RRadioGroupItem } from './radio/RRadio.vue'
export { default as RSwitch } from './switch/RSwitch.vue'
export { default as RTable, default as RTableHeader, default as RTableBody, default as RTableRow, default as RTableHead, default as RTableCell } from './table/RTable.vue'
export { default as RTableTh } from './table/RTableTh.vue'
export { default as RTabs } from './tabs/RTabs.vue'
export { default as RTabsList } from './tabs/RTabsList.vue'
export { default as RTabsTrigger } from './tabs/RTabsTrigger.vue'
export { default as RTabsContent } from './tabs/RTabsContent.vue'
export { default as RDialog, default as RDialogContent, default as RDialogHeader, default as RDialogTitle, default as RDialogFooter } from './dialog/RDialog.vue'
export { default as RDrawer, default as RDrawerContent } from './drawer/RDrawer.vue'
export { default as RSheet, default as RSheetContent } from './drawer/RDrawer.vue'
export { default as RTooltip } from './tooltip/RTooltip.vue'
export { default as RProgress } from './progress/RProgress.vue'
export { default as RAvatar, default as RAvatarImage, default as RAvatarFallback } from './avatar/RAvatar.vue'
export { default as RSkeleton } from './skeleton/RSkeleton.vue'
export { default as REmpty } from './empty/REmpty.vue'
export { default as RToast } from './toast/RToast.vue'
export { default as RPagination } from './pagination/RPagination.vue'
export { default as RAlert, default as RAlertTitle, default as RAlertDescription } from './alert/RAlert.vue'
export { default as RDropdown, default as RDropdownTrigger, default as RDropdownContent, default as RDropdownMenuItem } from './dropdown/RDropdown.vue'
export { default as RSeparator } from './separator/RSeparator.vue'
export { default as RScrollArea } from './scroll-area/RScrollArea.vue'
export { default as RLabel } from './label/RLabel.vue'
export { default as RPageShell } from './page-shell/RPageShell.vue'

// ═══ Backward-compatible aliases (deprecated, migrate to R-prefixed) ═══

export { default as Button } from './button/RButton.vue'
export { default as Card, default as CardHeader, default as CardTitle, default as CardContent, default as CardFooter } from './card/RCard.vue'
export { default as Badge } from './badge/RBadge.vue'
export { default as Input } from './input/RInput.vue'
export { default as Textarea } from './textarea/RTextarea.vue'
export { default as Select } from './select/RSelect.vue'
export { default as Checkbox } from './checkbox/RCheckbox.vue'
export { default as RadioGroup, default as RadioGroupItem } from './radio/RRadio.vue'
export { default as Switch } from './switch/RSwitch.vue'
export { default as Table, default as TableHeader, default as TableBody, default as TableRow, default as TableHead, default as TableCell } from './table/RTable.vue'
export { default as Tabs, default as TabsList, default as TabsTrigger, default as TabsContent } from './tabs/RTabs.vue'
export { default as Dialog, default as DialogContent, default as DialogHeader, default as DialogTitle, default as DialogFooter } from './dialog/RDialog.vue'
export { default as Sheet, default as SheetContent } from './drawer/RDrawer.vue'
export { default as Tooltip } from './tooltip/RTooltip.vue'
export { default as Progress } from './progress/RProgress.vue'
export { default as Avatar, default as AvatarImage, default as AvatarFallback } from './avatar/RAvatar.vue'
export { default as Skeleton } from './skeleton/RSkeleton.vue'
export { default as Pagination } from './pagination/RPagination.vue'
export { default as Alert, default as AlertTitle, default as AlertDescription } from './alert/RAlert.vue'
export { default as DropdownMenu, default as DropdownMenuTrigger, default as DropdownMenuContent, default as DropdownMenuItem } from './dropdown/RDropdown.vue'
export { default as Separator } from './separator/RSeparator.vue'
export { default as ScrollArea } from './scroll-area/RScrollArea.vue'
export { default as Label } from './label/RLabel.vue'
