import type { Component } from 'vue'
import {
  Eye,
  Pencil,
  Trash2,
  Send,
  CircleX,
  Monitor,
  FileText,
  Play,
  Pause,
  Wand2,
  FolderPlus,
  Link2,
  Plus,
  Search,
  RefreshCw,
  List,
  CircleCheck,
  Upload,
  Sparkles,
  BarChart3,
  Briefcase,
  LayoutGrid,
  Calendar,
  Ticket,
  CheckCircle,
  Files,
  Share2,
  Building2,
  MessageCircle,
  Activity,
  Filter,
  Users,
  Coins,
  Settings,
  Lock,
  User,
  Key,
  Stamp,
  ClipboardCheck,
  AlertTriangle,
  Timer,
  Zap,
  TrendingUp,
  TrendingDown,
  Kanban,
  Database,
  Bot,
  Scale,
  Funnel,
  Target,
  History,
  BookOpen,
  UserCog,
  Stethoscope,
  ClipboardList,
  PenTool,
  Shield,
  Brain,
  type LucideIcon,
} from 'lucide-vue-next'

const MAP: Record<string, LucideIcon> = {
  View: Eye,
  Edit: Pencil,
  Delete: Trash2,
  Promotion: Send,
  CircleClose: CircleX,
  Monitor,
  Document: FileText,
  VideoPlay: Play,
  VideoPause: Pause,
  MagicStick: Wand2,
  FolderAdd: FolderPlus,
  Connection: Link2,
  Plus,
  Search,
  RefreshRight: RefreshCw,
  List,
  CircleCheck,
  Upload,
  Sparkles,
  BarChart3,
  Briefcase,
  Grid: LayoutGrid,
  Calendar,
  Tickets: Ticket,
  Finished: CheckCircle,
  Files,
  Share: Share2,
  OfficeBuilding: Building2,
  ChatDotRound: MessageCircle,
  Activity,
  Filter,
  Users,
  Coin: Coins,
  Setting: Settings,
  Lock,
  UserFilled: User,
  Key,
  Stamp,
  ClipboardCheck,
  AlertTriangle,
  Timer,
  Zap,
  TrendingUp,
  TrendingDown,
  DataAnalysis: BarChart3,
  Notebook: FileText,
  Present: ClipboardCheck,
  Share2,
  DataLine: TrendingUp,
  ChatLineRound: MessageCircle,
  ChatSquare: MessageCircle,
  Box: Files,
  KanbanSquare: Kanban,
  Kanban,
  Database,
  Bot,
  Scale,
  Funnel,
  Target,
  History,
  BookOpen,
  UserCog,
  Stethoscope,
  ClipboardList,
  PenTool,
  OrganisationChart: Building2,
  Shield,
  Brain,
}

export function resolveActionIcon(icon?: string | Component): Component | undefined {
  if (!icon) return undefined
  if (typeof icon !== 'string') return icon
  return MAP[icon] ?? Eye
}
